### ISSUE TITLE
Crash when loading GoldenEye save state

### ISSUE THREAD

**Issue by loganmc10** [ricrpi/mupen64plus-audio-omx#4]
When using mupen64plus on a Raspberry Pi 3, I can save my state, but when I try to load a state, mupen64plus segfaults with this backtrace:

(gdb) backtrace
#0  __GI___libc_free (mem=0x1) at malloc.c:2929
#1  0x71854270 in vcil_out_FreeBuffer () from /opt/vc/lib/libopenmaxil.so

Backtrace stopped: previous frame identical to this frame (corrupt stack?)

I don't get this error when I use the SDL audio plugin (I figured this out because vcil_out_FreeBuffer seems to be an OMX thing based on my Googling)

**Comment by jjmerri** [comment]
Was this resolved? I am segfaulting when loading state too.

**Comment by loganmc10** [comment]
No I don't think it ever was

**Comment by jjmerri** [comment]
Thanks for getting back to me. I will open another issue.
